apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.fullname" . | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ include "petclinic.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "petclinic.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
